// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReportService.Api.Infrastructure.Persistence;

#nullable disable

namespace ReportService.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20260912221115_SeedDemoSignInEvents")]
    partial class SeedDemoSignInEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ReportService.Api.Domain.ReportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CountSignIn")
                        .HasColumnType("integer")
                        .HasColumnName("count_sign_in");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "ReportService.Api.Domain.ReportRequest.Period#DateRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("From")
                                .HasColumnType("date")
                                .HasColumnName("period_from");

                            b1.Property<DateOnly>("To")
                                .HasColumnType("date")
                                .HasColumnName("period_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_report_requests");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_report_requests_status_created_at");

                    b.ToTable("report_requests", (string)null);
                });

            modelBuilder.Entity("ReportService.Api.Domain.SignInEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sign_in_events");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("ix_sign_in_events_user_id_occurred_at");

                    b.ToTable("sign_in_events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000001"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000002"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 3, 9, 7, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000003"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 6, 9, 14, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000004"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 8, 9, 21, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000005"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 11, 9, 28, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000006"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 13, 9, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000007"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 16, 9, 42, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000008"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 19, 9, 49, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000009"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 21, 9, 56, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000000a"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 24, 10, 3, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000000b"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 26, 10, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000000c"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 29, 10, 17, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000000d"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000000e"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 4, 9, 7, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000000f"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 8, 9, 14, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000010"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 11, 9, 21, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000011"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 15, 9, 28, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000012"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 18, 9, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000013"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 22, 9, 42, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000014"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 25, 9, 49, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000015"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000016"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 7, 9, 7, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000017"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 13, 9, 14, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000018"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 19, 9, 21, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000019"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 25, 9, 28, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("b28d0ced-8af5-4c94-8650-c7946241fd1a")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000001a"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000001b"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 11, 9, 7, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000001c"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 21, 9, 14, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000001d"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000001e"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 2, 9, 7, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000001f"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 4, 9, 14, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000020"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 6, 9, 21, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000021"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 8, 9, 28, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000022"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 10, 9, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000023"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 12, 9, 42, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000024"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 14, 9, 49, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000025"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 15, 9, 56, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000026"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 17, 10, 3, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000027"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 19, 10, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000028"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 21, 10, 17, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000029"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 23, 10, 24, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000002a"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 25, 10, 31, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000002b"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 27, 10, 38, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000002c"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 1, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000002d"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 4, 9, 7, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000002e"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 7, 9, 14, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-00000000002f"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 11, 9, 21, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000030"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 14, 9, 28, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000031"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 18, 9, 35, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000032"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 21, 9, 42, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000033"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 25, 9, 49, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000034"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 28, 9, 56, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("4c1f9e2a-7b3d-4f8e-a6c5-2d9b0e1f3a7c")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000035"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 1, 31, 23, 59, 59, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("8e2d4b6a-1c3f-4a5e-9b7d-0f2a4c6e8b1d")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000036"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("8e2d4b6a-1c3f-4a5e-9b7d-0f2a4c6e8b1d")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000037"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 2, 28, 23, 59, 59, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("8e2d4b6a-1c3f-4a5e-9b7d-0f2a4c6e8b1d")
                        },
                        new
                        {
                            Id = new Guid("5eed0000-0000-0000-0000-000000000038"),
                            OccurredAt = new DateTimeOffset(new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UserId = new Guid("8e2d4b6a-1c3f-4a5e-9b7d-0f2a4c6e8b1d")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
